### ISSUE TITLE
Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/

### ISSUE THREAD

**Issue by Bluefire5** [PankajSavaliyaGit/SocialChat#1]
please tell, how to solve this problem.

**Comment by PankajSavaliya** [comment]
First you have to create project on firebase.then select **Authentication** on left side and select **SIGN-IN METHOD** to enable email and password method in provider

http://stackoverflow.com/questions/38010536/how-to-solve-the-error-projects-created-at-console-firebase-google-com-must-use
